[PF-2060] dockerize setup
doselect/docs.doselect.com pull request #94
Opened 2022-11-29 12:41 UTC by KrishnaGupta-Do

2022-11-29 12:51 UTC, chugh007 requested changes

2022-11-29 12:51 UTC, chugh007 commented on README.md
> +docker run -it -p "4567:4567" -v $PWD:/slate docs bash
docker run -it -p "4567:4567" -v $PWD:/slate docs - this command would start the server directly , no need for bash until we want to get inside container and run something other than server

2022-11-29 12:52 UTC, subrata-doselect approved these changes

2022-11-29 13:20 UTC, subrata-doselect approved these changes

2022-11-30 04:29 UTC, chugh007 approved these changes

2022-11-30 06:30 UTC, merged